// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// NewsConsumer is an autogenerated mock type for the NewsConsumer type
type NewsConsumer struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, quantity
func (_m *NewsConsumer) Fetch(ctx context.Context, quantity int) {
	_m.Called(ctx, quantity)
}

type mockConstructorTestingTNewNewsConsumer interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewsConsumer creates a new instance of NewsConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewsConsumer(t mockConstructorTestingTNewNewsConsumer) *NewsConsumer {
	mock := &NewsConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
