// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// XmlAdaptors is an autogenerated mock type for the XmlAdaptors type
type XmlAdaptors struct {
	mock.Mock
}

type mockConstructorTestingTNewXmlAdaptors interface {
	mock.TestingT
	Cleanup(func())
}

// NewXmlAdaptors creates a new instance of XmlAdaptors. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewXmlAdaptors(t mockConstructorTestingTNewXmlAdaptors) *XmlAdaptors {
	mock := &XmlAdaptors{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
